# Generated by Django 4.0.6 on 2022-08-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(default='some_editor', max_length=255),
        ),
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.CharField(default='noimage', max_length=255),
        ),
        migrations.AddField(
            model_name='content',
            name='info',
            field=models.TextField(default='NOinfo'),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='blogisnotcomplete', max_length=255),
        ),
    ]
