# Generated by Django 4.0.6 on 2022-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_blog_content_author_content_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
